In [1]:
#Import Modules
import pandas as pd
from bs4 import BeautifulSoup as bs
from splinter import Browser
import time
import json

In [2]:
#Initializing browser and setting its path
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
#Navigate to url for scraping
url = 'https://www.usinflationcalculator.com/inflation/current-inflation-rates/'
browser.visit(url)
time.sleep(1)

#Read html with pandas to create a df
inflate_html = pd.read_html(url)

#Convert to df and rename the columns, then for formatting remove index to keep end result clean
df = inflate_html[0]
df.columns = ["Year" , "Jan" , "Feb" , "Mar" , "Apr" , "May" , "Jun" , "Jul" , "Aug" , "Sep" , "Oct" , "Nov" , "Dec" , "Ave"]
df

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
0,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
1,2022,7.5,7.9,Avail. April 12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,1.4,1.7,2.6,4.2,5.0,5.4,5.4,5.3,5.4,6.2,6.8,7.0,4.7
3,2020,2.5,2.3,1.5,0.3,0.1,0.6,1.0,1.3,1.4,1.2,1.2,1.4,1.2
4,2019,1.6,1.5,1.9,2.0,1.8,1.6,1.8,1.7,1.7,1.8,2.1,2.3,1.8
5,2018,2.1,2.2,2.4,2.5,2.8,2.9,2.9,2.7,2.3,2.5,2.2,1.9,2.4
6,2017,2.5,2.7,2.4,2.2,1.9,1.6,1.7,1.9,2.2,2.0,2.2,2.1,2.1
7,2016,1.4,1.0,0.9,1.1,1.0,1.0,0.8,1.1,1.5,1.6,1.7,2.1,1.3
8,2015,-0.1,0.0,-0.1,-0.2,0.0,0.1,0.2,0.2,0.0,0.2,0.5,0.7,0.1
9,2014,1.6,1.1,1.5,2.0,2.1,2.1,2.0,1.7,1.7,1.7,1.3,0.8,1.6
10,2013,1.6,2.0,1.5,1.1,1.4,1.8,2.0,1.5,1.2,1.0,1.2,1.5,1.5
11,2012,2.9,2.9,2.7,2.3,1.7,1.7,1.4,1.7,2.0,2.2,1.8,1.7,2.1
12,2011,1.6,2.1,2.7,3.2,3.6,3.6,3.6,3.8,3.9,3.5,3.4,3.0,3.2
13,2010,2.6,2.1,2.3,2.2,2.0,1.1,1.2,1.1,1.1,1.2,1.1,1.5,1.6
14,2009,0,0.2,-0.4,-0.7,-1.3,-1.4,-2.1,-1.5,-1.3,-0.2,1.8,2.7,-0.4
15,2008,4.3,4.0,4.0,3.9,4.2,5.0,5.6,5.4,4.9,3.7,1.1,0.1,3.8
16,2007,2.1,2.4,2.8,2.6,2.7,2.7,2.4,2.0,2.8,3.5,4.3,4.1,2.8
17,2006,4.0,3.6,3.4,3.5,4.2,4.3,4.1,3.8,2.1,1.3,2.0,2.5,3.2
18,2005,3.0,3.0,3.1,3.5,2.8,2.5,3.2,3.6,4.7,4.3,3.5,3.4,3.4
19,2004,1.9,1.7,1.7,2.3,3.1,3.3,3.0,2.7,2.5,3.2,3.5,3.3,2.7
20,2003,2.6,3.0,3.0,2.2,2.1,2.1,2.1,2.2,2.3,2.0,1.8,1.9,2.3
21,2002,1.1,1.1,1.5,1.6,1.2,1.1,1.5,1.8,1.5,2.0,2.2,2.4,1.6
22,2001,3.7,3.5,2.9,3.3,3.6,3.2,2.7,2.7,2.6,2.1,1.9,1.6,2.8
23,2000,2.7,3.2,3.8,3.1,3.2,3.7,3.7,3.4,3.5,3.4,3.4,3.4,3.4

In [4]:
df_del = df.drop(0)
clean_df = df_del.drop(1)
clean_df.reset_index()
clean_df.columns.name = None

table = clean_df[['Year', 'Ave']]
table.to_csv("../data/inflation.csv", index=False)
table

    Year   Ave
2   2021   4.7
3   2020   1.2
4   2019   1.8
5   2018   2.4
6   2017   2.1
7   2016   1.3
8   2015   0.1
9   2014   1.6
10  2013   1.5
11  2012   2.1
12  2011   3.2
13  2010   1.6
14  2009  -0.4
15  2008   3.8
16  2007   2.8
17  2006   3.2
18  2005   3.4
19  2004   2.7
20  2003   2.3
21  2002   1.6
22  2001   2.8
23  2000   3.4